---
name: example-kafka-on-demand
label: On-Demand Kafka
description: Kafka on-demand tile for example purposes

metadata_version: "1.8"
product_version: $( version )

my_release_version: $( release "on-demand-service-broker" | select "version" )
minimum_version_for_upgrade: 0.17.0

# service_broker: true can be commented out to avoid bosh director redeployments on tile installation/deletion.
# In that case make sure to hardcode everything that comes from $self below.
service_broker: true

provides_product_versions:
- name: example-kafka-on-demand
  version: $( version )

requires_product_versions:
- name: cf
  version: ">= 2.4"

icon_image: $( icon )

rank: 90
serial: false

post_deploy_errands:
- name: register-broker
  colocated: true
  label: Register On Demand Service Broker
  instances: [broker/first]

- name: upgrade-all-service-instances
  colocated: true
  label: Upgrade All Service Instances
  description: Upgrade all deployed service instances
  instances: [broker/first]

- name: recreate-all-service-instances
  colocated: true
  run_default: false
  label: Recreate All Service Instances
  description: Recreate all deployed service instances
  instances: [broker/first]

- name: orphan-deployments
  colocated: true
  run_default: false
  label: Orphan Deployments
  description: Detect orphan deployment instances
  instances: [broker/first]

pre_delete_errands:
- name: delete-all-service-instances-and-deregister-broker
  label: Delete All Service Instances and Deregister Broker
  description: Delete all deployed service instances and deregister the broker
  colocated: true
  instances: [broker/first]

- name: delete-all-service-instances
  label: Delete All Service Instances
  description: Delete all deployed service instances
  colocated: true
  run_default: false
  instances: [broker/first]

- name: deregister-broker
  label: Deregister Broker
  description: Deregister the broker
  colocated: true
  run_default: false
  instances: [broker/first]

releases:
- $( release "on-demand-service-broker" )
- $( release "kafka-example-service-adapter" )
- $( release "kafka-example-service" )
- $( release "consul" )
- $( release "bpm" )

stemcell_criteria: $( stemcell )

property_blueprints:
- $( property "secure-bindings" )
- $( property "resolve_secrets_at_bind" )

form_types:
- $( form "on-demand-broker" )
- $( form "plan-1" )
- $( form "plan-2" )
- $( form "service-instances-upgrade" )

job_types:
- $( instance_group "broker" )
